FROM golang:latest AS building

COPY . /building
WORKDIR /building

RUN make frps

FROM alpine:latest

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]
