FROM golang:latest AS building

COPY . /building
WORKDIR /building

RUN make frpc

FROM alpine:latest

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT ["/usr/bin/frpc"]
